/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "vbproto_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LockRequest, LockRequest, AUTO)


PB_BIND(LockedInfo, LockedInfo, AUTO)


PB_BIND(LockResponse, LockResponse, AUTO)


PB_BIND(Payload, Payload, AUTO)


PB_BIND(VBProto, VBProto, AUTO)


PB_BIND(FileEventMeta, FileEventMeta, AUTO)


PB_BIND(FileEventBatch, FileEventBatch, 8)


PB_BIND(RegisterDirectoryRequest, RegisterDirectoryRequest, AUTO)



